import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <nav>
          {/* app에 있는 page로 감. */}
          <Link href={"/"}>
            <p>Home</p>
          </Link>
          {/* posts 폴더에 있는 페이지로 이동 */}
          <Link href={"/posts"}>
            <p>Post</p>
          </Link>
        </nav>
        <main>
        {children}
        </main>
      </body>
    </html>
  );
}
