import type { Metadata } from "next";
import "./globals.css";
import Link from "next/link";
import { Control } from "./Control";

export type topicsType = {
  id: string,
  title: string,
  body: string,
}

export const metadata: Metadata = {
  title: "Web tutorials",
  description: "Generated by mingu",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const res = await fetch("http://localhost:9999/topics",{cache: "no-store"});
  const topics: topicsType[] = await res.json();
  
  return (
    <html>
      <body>
        {/* a태그로 페이지 이동 시 이동 할 때마다 페이지를 다시 다운로드를 함.
        Link태그를 사용하면 다시 다운로드 하는 현상을 막을 수 있음. */}
        <h1><Link href="/">WEB</Link></h1>
        <ol>
          {topics.map((topic) => (
            <li key={topic.id}><Link href={`/read/${topic.id}`}>{topic.title}</Link></li>
          ))}
        </ol>
        {children}
        <Control/>
      </body>
    </html>
  );
}
